### ISSUE TITLE
device_configuration/cam.txt问题

### ISSUE THREAD

**Issue by xiaojin-code** [BeAShaper/appearance-scanner#1]
前辈，您好！目前想咨询一下，您在github上提到的，要把device_configuration/cam.txt的相机参数复制到colmap，如果我这边想用自己的图片测试的话，相机参数要如何设置啊？
以上是我想提问的问题，特别想得到您的指导，期待您的回复！

**Comment by BeAShaper** [comment]
如果知道拍摄图片的相机的intrinsic，在colmap中选择camera model为OPENCV，把camera matrix中的f_x，c_x，f_y，c_y填到colmap的custom parameters中（后面加4个0.0，和cam.txt格式一致）
如果不知道相机内参，选择合适的相机模型，默认使用Parameters from EXIF就可以

**Comment by xiaojin-code** [comment]
啊啊好的，太感谢了。
我这边还有一个问题是，3.2 Further Alignment中run CoherentPointDrift/CoherentPointDrift-master/simplify/run.bat时，因为我用的是自己的数据重建的点云，所以跟您的SET SIMPLIFY_PATH=../../mesh/目录中的X.ply，Y.ply不一致，
我想问下，我如何才能生成跟我数据匹配的X.ply，Y.ply文件？
另外，我想再问下，X.ply，Y.ply具体代表什么含义的点云数据啊？
再次期待您的答疑，感激不尽！

**Comment by BeAShaper** [comment]
X.ply，Y.ply是CoherentPointDrift/CoherentPointDrift-master/simplify/run.bat的输出，输入是两个要对齐的点云，因为原始点云点可能很多，size太大，可以先简化再进行对齐，所以你直接准备好要对齐的两个点云，设置好路径直接运行就可以

**Comment by xiaojin-code** [comment]
前辈，我目前按照你给的提示问题解决了，目前运行到了4.1 Remesh run ACVD/aarun.bat路径已修改为我的数据所在目录，现在运行中vtkOutputWindow窗口提示2个报错：
一、’‘PLY error reading file.Premature EOF while reading double’‘
二、’‘PLY error reading file.Premature EOF while reading uchar or uint8’‘
我目前在aarun.bat中的
SET DATA_ROOT=E:/3d_deep_creat/appearance-scanner-main/appearance_scanner/data/Cheongsam/undistort_feature/
SET FILE=%DATA_ROOT%meshed-poisson_obj.ply
SET FILE_O=meshed-poisson_obj_remeshed.ply
SET NVERTICES=100000
SET GRADATION=0
其中SET NVERTICES=100000，SET GRADATION=0按照默认没有修改，最后在../undistort_feature/文件中没有生成meshed-poisson_obj_remeshed.ply，请问前辈能否告知是什么原因以及解决方法？十分感激~~~

**Comment by BeAShaper** [comment]
你用的是旗袍的数据吗？
报错的原因是这样
```
if (!plyfile->is->good())
{
  vtkGenericWarningMacro("PLY error reading file."
    << " Premature EOF while reading uchar or uint8.");
  return false;
}
```
你检查一下meshed-poisson_obj.ply有没有问题，能不能用meshlab打开

**Comment by xiaojin-code** [comment]
我用的自己重建的数据，不是旗袍的数据，刚才检查了meshed-poisson_obj.ply，能用meshlab打开，是SET NVERTICES=100000，SET GRADATION=0参数设定需要修改吗？

**Comment by BeAShaper** [comment]
你加我微信mg970734538我给你看一下吧
